# Generated by Django 4.2 on 2023-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("updated_at", models.DateTimeField(auto_created=True)),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(default="", max_length=50, unique=True)),
                ("password", models.CharField(default="", max_length=100)),
                ("nickname", models.CharField(default="", max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
