# Generated by Django 4.2 on 2023-04-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="created_at",),
        migrations.RemoveField(model_name="user", name="updated_at",),
    ]
