# Generated by Django 4.2 on 2023-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_created_at_remove_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
