# Generated by Django 4.2 on 2023-04-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sub_category", "0003_alter_subcategory_category"),
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="sub_category.subcategory",
            ),
        ),
    ]
