# Generated by Django 4.2 on 2023-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Deleted", "Deleted"),
                ],
                default="Pending",
            ),
        ),
    ]
