# Generated by Django 4.2 on 2023-04-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0002_license_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="category_sport",
            new_name="category",
        ),
    ]
